import { Contest } from './types';

export const MOCK_CONTESTS: Contest[] = [
  {
    id: 'c1',
    title: 'General Knowledge Gala',
    description: 'Test your all-around knowledge in this classic trivia showdown.',
    category: 'General Knowledge',
    entryFee: 0,
    prizePool: 500,
    status: 'Upcoming',
    registrationStartDate: Date.now() - 24 * 60 * 60 * 1000, // Started yesterday
    registrationEndDate: Date.now() + 6 * 24 * 60 * 60 * 1000, // Ends in 6 days
    contestStartDate: Date.now() + 6 * 24 * 60 * 60 * 1000 + 3600000, // Starts 1 hour after registration ends
    maxParticipants: 200,
    rules: 'Standard quiz rules. No cheating allowed. The admin\'s decision is final.',
    questions: [], // These would be populated by an admin
    participants: ['test@user.com'],
    format: 'KBC',
    timerType: 'per_question',
    timePerQuestion: 30,
    numberOfQuestions: 15,
  },
  {
    id: 'c2',
    title: 'Science Sphere Challenge',
    description: 'From biology to astrophysics, prove you are a science whiz.',
    category: 'Science & Nature',
    entryFee: 100,
    prizePool: 10000,
    status: 'Upcoming',
    registrationStartDate: Date.now(),
    registrationEndDate: Date.now() + 10 * 24 * 60 * 60 * 1000,
    contestStartDate: Date.now() + 10 * 24 * 60 * 60 * 1000 + 3600000,
    maxParticipants: 100,
    rules: 'Science category only. All questions are peer-reviewed for accuracy.',
    questions: [],
    participants: [],
    format: 'KBC',
    timerType: 'per_question',
    timePerQuestion: 45,
    numberOfQuestions: 15,
  },
  {
    id: 'c3',
    title: 'History Buffs Battle',
    description: 'Journey through time and test your historical expertise.',
    category: 'History',
    entryFee: 50,
    prizePool: 5000,
    status: 'Upcoming',
    registrationStartDate: Date.now(),
    registrationEndDate: Date.now() + 5 * 24 * 60 * 60 * 1000,
    contestStartDate: Date.now() + 5 * 24 * 60 * 60 * 1000 + 3600000,
    maxParticipants: 150,
    rules: 'Focuses on world history from ancient civilizations to the 20th century.',
    questions: [],
    participants: [],
    format: 'KBC',
    timerType: 'per_question',
    timePerQuestion: 35,
    numberOfQuestions: 15,
  },
  {
    id: 'c4',
    title: 'Movie Marathon Quiz',
    description: 'Are you a true cinephile? This one is for you!',
    category: 'Movies & TV',
    entryFee: 0,
    prizePool: 250,
    status: 'Finished',
    registrationStartDate: Date.now() - 20 * 24 * 60 * 60 * 1000,
    registrationEndDate: Date.now() - 15 * 24 * 60 * 60 * 1000,
    contestStartDate: Date.now() - 15 * 24 * 60 * 60 * 1000 + 3600000,
    maxParticipants: 500,
    rules: 'Questions cover a wide range of genres and eras.',
    questions: [],
    participants: [],
    format: 'KBC',
    timerType: 'per_question',
    timePerQuestion: 25,
    numberOfQuestions: 15,
  },
    {
    id: 'c5',
    title: 'Sports Fan Standoff',
    description: 'Go for the gold in this ultimate sports trivia competition.',
    category: 'Sports',
    entryFee: 25,
    prizePool: 2500,
    status: 'Upcoming',
    registrationStartDate: Date.now(),
    registrationEndDate: Date.now() + 3 * 24 * 60 * 60 * 1000,
    contestStartDate: Date.now() + 3 * 24 * 60 * 60 * 1000 + 3600000,
    maxParticipants: 75,
    rules: 'All sports, all eras. Test your knowledge across the board.',
    questions: [],
    participants: [],
    format: 'KBC',
    timerType: 'per_question',
    timePerQuestion: 30,
    numberOfQuestions: 15,
  },
  {
    id: 'c6',
    title: 'Tech Titans Tussle',
    description: 'Code, gadgets, and the digital world. Show off your tech genius.',
    category: 'Technology',
    entryFee: 200,
    prizePool: 20000,
    status: 'Draft', // Example of a draft contest
    registrationStartDate: Date.now() + 2 * 24 * 60 * 60 * 1000,
    registrationEndDate: Date.now() + 9 * 24 * 60 * 60 * 1000,
    contestStartDate: Date.now() + 9 * 24 * 60 * 60 * 1000 + 3600000,
    maxParticipants: 50,
    rules: 'High-level technology questions. For experts only.',
    questions: [],
    participants: [],
    format: 'KBC',
    timerType: 'per_question',
    timePerQuestion: 60,
    numberOfQuestions: 15,
  },
];